# Generated by Django 5.0.6 on 2024-06-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_brand_product_image_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='Lorem ipsum', max_length=2000),
        ),
    ]
