# Generated by Django 5.0.6 on 2024-05-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
