# Generated by Django 5.0.6 on 2024-05-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.CharField(blank=True, default='', max_length=200, unique=True),
        ),
    ]
